package Vistas;

import Controlador.EntregaDAO;
import Controlador.PedidoDAO;
import Controlador.RepartidorDAO;
import Modelo.Entrega;
import Modelo.EstadoPedido;
import Modelo.Pedidos;
import Modelo.Repartidor;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class VentanaAsignarEntrega extends JFrame {

    private JComboBox<Pedidos> comboPedidos;
    private JComboBox<Repartidor> comboRepartidores;
    private JButton btnAsignar;

    public VentanaAsignarEntrega() {

        setTitle("Asignar Entrega - SpeedFast");
        setSize(400, 250);
        setLocationRelativeTo(null);
        setLayout(new GridLayout(3, 2, 10, 10));

        // CARGA DE DATOS

        PedidoDAO pDao = new PedidoDAO();
        RepartidorDAO rDao = new RepartidorDAO();

        add(new JLabel("Seleccionar Pedido:"));
        comboPedidos = new JComboBox<>();
        pDao.listarTodos().forEach(comboPedidos::addItem);
        add(comboPedidos);

        add(new JLabel("Seleccionar Repartidor:"));
        comboRepartidores = new JComboBox<>();
        rDao.listarTodos().forEach(comboRepartidores::addItem);
        add(comboRepartidores);

        btnAsignar = new JButton("Registrar Entrega");
        add(new JLabel("")); // Espacio vacío
        add(btnAsignar);

        btnAsignar.addActionListener(e -> registrar());
    }

    private void registrar() {
        Pedidos p = (Pedidos) comboPedidos.getSelectedItem();
        Repartidor r = (Repartidor) comboRepartidores.getSelectedItem();

        if (p == null || r == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un pedido y un repartidor", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //PEDIDOS PENDIENTES

        if (p.getEstado() != EstadoPedido.PENDIENTE) {
            JOptionPane.showMessageDialog(this,
                    "No se puede asignar: El pedido ya está " + p.getEstado(),
                    "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // VALIDACION

        Entrega entrega = new Entrega(p.getId(), r.getId());
        EntregaDAO eDao = new EntregaDAO();


        //ACTUALIZACION DEL PEDIDO

        p.setEstado(EstadoPedido.EN_REPARTO);
        PedidoDAO pDao = new PedidoDAO();
        pDao.actualizar(p); // Usamos tu método actualizar

        eDao.guardar(entrega);
        JOptionPane.showMessageDialog(this, "Entrega asignada y pedido actualizado a EN_REPARTO.");
        dispose();

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
