package Vistas;

import Controlador.PedidoDAO;
import Modelo.Pedidos;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class VentanaRegistroPedido extends JFrame {

    private JPanel panel1;
    private ArrayList<Pedidos> listaPedidos;
    private JTextField columId;
    private JTextField columDirecion;
    private JComboBox<String> comboBoxTipo;
    private JComboBox<String> comboBoxEstado;


    public VentanaRegistroPedido(ArrayList<Pedidos> listaPedido) {
        this.listaPedidos = listaPedido;

        setTitle("Registro - Nuevo Pedido");
        setSize(500, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new GridLayout(3, 1, 5, 5));

        add(new JLabel("ID Pedido:"));
        columId = new JTextField();
        add(columId);

        add(new JLabel("Direccion"));
        columDirecion = new JTextField();
        add(columDirecion);

        add(new JLabel("Tipo"));
        comboBoxTipo = new JComboBox<>(new String[]{"Comida", "Encomienda", "Express"});
        add(comboBoxTipo);

        add(new JLabel("Estado"));
        comboBoxEstado = new JComboBox<>(new String[]{"PREPARANDO", "RECOGIDO", "ENTREGADO"});
        add(comboBoxEstado);


        JButton btnGuardar = new JButton("Guardar");
        add(new JLabel(""));
        add(btnGuardar);

        btnGuardar.addActionListener(e -> guardarPedidos());
    }

    private void guardarPedidos() {
        String id = columId.getText().trim();
        String direccion = columDirecion.getText().trim();
        String tipo = (String) comboBoxTipo.getSelectedItem();
        String estado = (String) comboBoxEstado.getSelectedItem();

        if (id.isEmpty() || direccion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos soin obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Pedidos pedido = new Pedidos(id, direccion, tipo, estado);
        listaPedidos.add(pedido);

        PedidoDAO dao = new PedidoDAO();
        dao.guardar(pedido);

        JOptionPane.showMessageDialog(this, "Pedido registrado exitosamente", "Registro", JOptionPane.INFORMATION_MESSAGE);


        columId.setText("");
        columDirecion.setText("");

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        columId = new JTextField();
        columId.setText("ID");
        panel1.add(columId, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        columDirecion = new JTextField();
        columDirecion.setText("Direccion");
        panel1.add(columDirecion, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        comboBoxTipo = new JComboBox();
        comboBoxTipo.setToolTipText("Tipo");
        panel1.add(comboBoxTipo, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}





