package Vistas;

import Modelo.Pedidos;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;

public class VentanaListaPedido extends JFrame {

    private ArrayList<Pedidos> listaPedidos;
    private JTable tablaPedidos;
    private DefaultTableModel modeloTabla;

    public VentanaListaPedido(ArrayList<Pedidos> listaPedidos) {
        this.listaPedidos = listaPedidos;

        setTitle("Lista de Pedidos");
        setSize(500, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout(5, 5));

        String[] columns = {"ID", "Direccion", "Tipo", "Estado"};
        modeloTabla = new DefaultTableModel(columns, 0);
        tablaPedidos = new JTable(modeloTabla);

        JScrollPane scrollPane = new JScrollPane(tablaPedidos);
        add(scrollPane, BorderLayout.CENTER);

        JButton botonRefrescar = new JButton("Refrescar");
        add(botonRefrescar, BorderLayout.SOUTH);

        cargarDatos();

        botonRefrescar.addActionListener(e -> cargarDatos());

    }

    private void cargarDatos() {

        modeloTabla.setRowCount(0);
        for (Pedidos pedidos : listaPedidos) {
            Object[] fila = {pedidos.getId(), pedidos.getDireccion(), pedidos.getTipo(), pedidos.getEstado()};
            modeloTabla.addRow(fila);


        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}

